import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/Component/Shared/Footer";
import Navbar from "@/Component/Shared/Navbar";
import { ToastContainer } from "react-toastify";

const josefin = Josefin_Sans({

  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Navbar></Navbar>
        <main className="grow">
          {children}
        </main>
        <ToastContainer />
        <Footer></Footer>
      </body>
    </html>
  );
}
